# Eksperimentelle tjenester

In [1]:
!pip install dhlab

Requirement already satisfied: dhlab in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (2.23.0)
Requirement already satisfied: beautifulsoup4 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from dhlab) (4.11.2)
Requirement already satisfied: python-louvain in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from dhlab) (0.16)
Requirement already satisfied: pandas in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from dhlab) (1.5.3)
Requirement already satisfied: matplotlib in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from dhlab) (3.7.0)
Requirement already satisfied: requests in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from dhlab) (2.28.2)
Requirement already satisfied: Pillow in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from dhlab) (9.4.0)
Requirement already satisfied: IPython in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from dhlab) (8.10.0)
Requirement already satisfied: seaborn in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from dhlab) (0.12.2)
Requirement already satisfied: networkx in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from dhlab) (3.0)
Requirement already satisfied: soupsieve>1.2 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from beautifulsoup4->dhlab) (2.3.2.post1)
Requirement already satisfied: matplotlib-inline in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from IPython->dhlab) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.30 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from IPython->dhlab) (3.0.36)
Requirement already satisfied: traitlets>=5 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from IPython->dhlab) (5.9.0)
Requirement already satisfied: pygments>=2.4.0 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from IPython->dhlab) (2.14.0)
Requirement already satisfied: stack-data in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from IPython->dhlab) (0.6.2)
Requirement already satisfied: jedi>=0.16 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from IPython->dhlab) (0.18.2)
Requirement already satisfied: pickleshare in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from IPython->dhlab) (0.7.5)
Requirement already satisfied: backcall in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from IPython->dhlab) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from IPython->dhlab) (4.8.0)
Requirement already satisfied: decorator in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from IPython->dhlab) (5.1.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from matplotlib->dhlab) (4.38.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from matplotlib->dhlab) (3.0.9)
Requirement already satisfied: numpy>=1.20 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from matplotlib->dhlab) (1.24.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from matplotlib->dhlab) (1.0.7)
Requirement already satisfied: packaging>=20.0 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from matplotlib->dhlab) (23.0)
Requirement already satisfied: cycler>=0.10 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from matplotlib->dhlab) (0.11.0)
Requirement already satisfied: python-dateutil>=2.7 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from matplotlib->dhlab) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from matplotlib->dhlab) (1.4.4)
Requirement already satisfied: pytz>=2020.1 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from pandas->dhlab) (2022.7.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from requests->dhlab) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from requests->dhlab) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from requests->dhlab) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from requests->dhlab) (3.0.1)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from jedi>=0.16->IPython->dhlab) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from pexpect>4.3->IPython->dhlab) (0.7.0)
Requirement already satisfied: wcwidth in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from prompt-toolkit<3.1.0,>=3.0.30->IPython->dhlab) (0.2.6)
Requirement already satisfied: six>=1.5 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->dhlab) (1.16.0)
Requirement already satisfied: executing>=1.2.0 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from stack-data->IPython->dhlab) (1.2.0)
Requirement already satisfied: pure-eval in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from stack-data->IPython->dhlab) (0.2.2)
Requirement already satisfied: asttokens>=2.1.0 in /home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages (from stack-data->IPython->dhlab) (2.2.1)

In [2]:
from dhlab.future.corpus_conc_coll import Corpus, Concordance, Collocations, Frequencies

In [3]:
c = Corpus.build(doctype="digibok")
c.head(2)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [5]:
c.get_freqs().display_names()

          Drakevind : dikt  ...  En vise om Halsen
.                    182.0  ...               54.0
,                    124.0  ...               61.0
i                    120.0  ...               14.0
og                    98.0  ...               42.0
ein                   50.0  ...                0.0
...                    ...  ...                ...
gaat                   0.0  ...                2.0
stokker                0.0  ...                2.0
Stjørdal               0.0  ...                3.0
sælger                 0.0  ...                4.0
Hognes                 0.0  ...               12.0

[38700 rows x 10 columns]

In [17]:
c.get_freqs().sum_freqs()

          frequencies
.             27099.0
,             22082.0
i              6247.0
og            10107.0
ein              50.0
...               ...
gaat              2.0
stokker           2.0
Stjørdal          3.0
sælger            4.0
Hognes           12.0

[38700 rows x 1 columns]

In [16]:
Concordance.get_concordances(corpus=c, words="konge").head()

       docid  ...                                               link
0  100223129  ...  <a target='_blank' href = 'https://urn.nb.no/U...
1  100223129  ...  <a target='_blank' href = 'https://urn.nb.no/U...
2  100223129  ...  <a target='_blank' href = 'https://urn.nb.no/U...
3  100223129  ...  <a target='_blank' href = 'https://urn.nb.no/U...
4  100223129  ...  <a target='_blank' href = 'https://urn.nb.no/U...

[5 rows x 4 columns]

In [14]:
Collocations.get_collocations(corpus=c, words=["konge", "kongeriket"])

               counts
,                32.0
representerer     2.0
Vi                2.0
kom               2.0
satt              2.0
...               ...
d                 2.0
kan               2.0
-                 4.0
konge             2.0
unge              2.0

[256 rows x 1 columns]